# Main configuration
title: discord.py-self
description: A fork of the popular Discord.py for self-bots. 
remote_theme: pmarsceill/just-the-docs
url: 'https://dolf.ml'
baseurl: /discord.py-self

# Theme settings
aux_links_new_tab: true
color_scheme: dark
gh_edit_link: false
last_edit_timestamp: false

aux_links:
  "GitHub":
    - "//github.com/dolfies/discord.py-self"
  "Releases":
    - "//github.com/dolfies/discord.py-self/releases"
  "PyPi":
    - "//pypi.org/project/discord.py-self"
